[package]
name = "clamchowder"
version = "0.1.0"
authors = ["Ian S. Pringle <ipringle2@liberty.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clamav-rs = "0.5"
rocket = "0.4"
